# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='mentorsesh',
        ),
        migrations.RemoveField(
            model_name='host',
            name='session',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ta',
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='session',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='ta',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
