# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Enroll',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enroll2',
            fields=[
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='sid_enroll2_set', serialize=False, to='takai.Students')),
            ],
            options={
                'db_table': 'Enroll2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Mentor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mentorsessions',
            fields=[
                ('time', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Mentorsessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('officehours', models.CharField(blank=True, db_column='officeHours', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1500, null=True)),
                ('picture', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'TA',
                'managed': False,
            },
        ),
    ]
