# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorsesh', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Mentorsessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Students')),
                ('theclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Classes')),
            ],
            options={
                'db_table': 'Host',
                'managed': True,
            },
        ),
    ]
