# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Session'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Students'),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set([('student', 'session')]),
        ),
    ]
