# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0002_auto_20180412_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorsesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Mentorsessions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Session')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Ta')),
            ],
            options={
                'db_table': 'Host',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Session')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Ta')),
            ],
            options={
                'db_table': 'Mentor',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='mentor',
            unique_together=set([('ta', 'session')]),
        ),
    ]
