# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='theclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Session'),
        ),
    ]
