# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0002_enroll_enroll2_mentor_mentorsessions_professors_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Teach',
                'managed': False,
            },
        ),
    ]
