# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0003_auto_20180412_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=100)),
                ('qualities', models.CharField(max_length=1500)),
                ('num_hours_week', models.FloatField()),
                ('lab_availability', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Students')),
            ],
            options={
                'db_table': 'Application',
                'managed': True,
            },
        ),
    ]
