# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takai', '0007_auto_20180426_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Availability',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Availabilitycode',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('meaning', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Availabilitycode',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='availabilitycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='takai.Availabilitycode'),
        ),
        migrations.AddField(
            model_name='availability',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takai.Students'),
        ),
    ]
